import React, { useState, useEffect, useRef } from 'react';
import { useAuth } from '../../context/AuthContext';
import './DailySpinner.scss';
import SpinRewardPopup from './SpinRewardPopup';
import PaymentModal from './PaymentModal';

const DailySpinner = ({ onSpinEnd }) => {
  // Wheel configuration - low rewards are common, high rewards are intentionally rare
  const WHEEL_VALUES = [1, 2, 3, 5, 10, 20, 50, 100, 200, 300, 500];
  // Backend-aligned display weights
  const WEIGHTS = [50, 30, 10, 5, 3, 1, 0.6, 0.3, 0.07, 0.02, 0.01];
  const SEGMENT_COLORS = [
    '#FDE2E2', '#FFE9D6', '#FFF1CC', '#E8F5E9', '#E3F2FD',
    '#EDE7F6', '#FCE4EC', '#FFF8E1', '#D7CCC8', '#F5F5F5', '#E1F5FE'
  ];
  
  // State
  const [loading, setLoading] = useState(true);
  const [hasSpunToday, setHasSpunToday] = useState(false);
  const [timeUntilNextSpin, setTimeUntilNextSpin] = useState(null);
  const [isSpinning, setIsSpinning] = useState(false);
  const [reward, setReward] = useState(null);
  const [showRewardPopup, setShowRewardPopup] = useState(false);
  const [extraSpinsBalance, setExtraSpinsBalance] = useState(0);
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [paymentOption, setPaymentOption] = useState(null);
  const [error, setError] = useState(null);
  
  const { user } = useAuth();
  const wheelRef = useRef(null);
  const rotationRef = useRef(0);

  const wheelSegments = WHEEL_VALUES.map((value, index) => ({
    value,
    weight: WEIGHTS[index],
    color: SEGMENT_COLORS[index % SEGMENT_COLORS.length],
  }));
  const sliceAngle = 360 / wheelSegments.length;
  const conicGradient = `conic-gradient(${wheelSegments
    .map((segment, index) => {
      const start = index * sliceAngle;
      const end = (index + 1) * sliceAngle;
      return `${segment.color} ${start}deg ${end}deg`;
    })
    .join(', ')})`;

  // Check daily spin status from database
  useEffect(() => {
    if (!user?.id) return;
    checkDailySpinStatusFromDB();
  }, [user?.id]);

  const checkDailySpinStatusFromDB = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/game/spin-status/${user.id}`);
      
      if (!response.ok) throw new Error('Failed to fetch spin status');
      
      const data = await response.json();
      
      setHasSpunToday(data.hasSpunToday);
      setExtraSpinsBalance(data.extraSpinsBalance || 0);
      
      if (data.hasSpunToday) {
        setTimeUntilNextSpin(data.timeUntilNextSpin);
        const timer = setInterval(() => {
          updateTimeUntilNextSpin();
        }, 1000);
        return () => clearInterval(timer);
      }
    } catch (err) {
      console.error('Error checking spin status:', err);
      setError('Failed to load spin status');
    } finally {
      setLoading(false);
    }
  };

  const updateTimeUntilNextSpin = async () => {
    try {
      const response = await fetch(`/api/game/time-until-spin/${user.id}`);
      if (response.ok) {
        const data = await response.json();
        setTimeUntilNextSpin(data.timeRemaining);
      }
    } catch (err) {
      console.error('Error updating countdown:', err);
    }
  };

  // Animate the wheel and save result
  const spinWheel = async () => {
    if (isSpinning) return;
    if (hasSpunToday && extraSpinsBalance === 0) return;
    if (!user?.id) return;

    try {
      setError(null);
      setIsSpinning(true);

      // Ask backend to generate and record reward (source of truth)
      const spinResponse = await fetch('/api/game/record-spin', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userId: user.id,
          usedExtraSpin: extraSpinsBalance > 0 && hasSpunToday,
          timestamp: new Date().toISOString(),
        }),
      });

      if (!spinResponse.ok) {
        const errorData = await spinResponse.json().catch(() => ({}));
        throw new Error(errorData.error || 'Failed to record spin');
      }

      const spinData = await spinResponse.json();
      const winningValue = Number(spinData.rewardAmount || 1);
      const winningIndex = WHEEL_VALUES.indexOf(winningValue);

      if (winningIndex < 0) {
        throw new Error('Invalid reward generated by server');
      }
      
      // Calculate rotation so winning segment center lands at top pointer (270deg in CSS polar axis)
      const segmentCenterAngle = winningIndex * sliceAngle + sliceAngle / 2;
      const randomExtraSpins = 5 + Math.floor(Math.random() * 3); // 5-7 full spins
      const pointerAlignment = 270 - segmentCenterAngle;
      const targetRotation = randomExtraSpins * 360 + pointerAlignment;
      
      // Animate the spin
      const startRotation = rotationRef.current;
      const startTime = Date.now();
      const spinDuration = 3000; // 3 seconds

      const animate = () => {
        const elapsed = Date.now() - startTime;
        const progress = Math.min(elapsed / spinDuration, 1);
        
        // Easing function for smooth deceleration
        const easeOut = 1 - Math.pow(1 - progress, 3);
        
        const currentRotation = startRotation + (targetRotation - startRotation) * easeOut;
        rotationRef.current = currentRotation % 360;
        
        if (wheelRef.current) {
          wheelRef.current.style.transform = `rotate(${currentRotation}deg)`;
        }

        if (progress < 1) {
          requestAnimationFrame(animate);
        } else {
          setIsSpinning(false);
          setReward({
            amount: winningValue,
            transactionId: spinData.transactionId,
            walletId: spinData.walletId,
          });
          setShowRewardPopup(true);

          setHasSpunToday(true);
          setExtraSpinsBalance(spinData.remainingExtraSpins ?? Math.max(extraSpinsBalance - 1, 0));
          checkDailySpinStatusFromDB();
        }
      };

      requestAnimationFrame(animate);
    } catch (err) {
      setError('Error during spin');
      setIsSpinning(false);
    }
  };

  const handleBuyExtraSpin = (option) => {
    setPaymentOption(option);
    setShowPaymentModal(true);
  };

  const handlePaymentSuccess = async () => {
    try {
      // Refresh extra spins balance from DB
      const response = await fetch(`/api/game/extra-spins/${user.id}`);
      if (response.ok) {
        const data = await response.json();
        setExtraSpinsBalance(data.balance);
      }
      setShowPaymentModal(false);
      setPaymentOption(null);
    } catch (err) {
      console.error('Error refreshing balance:', err);
    }
  };

  if (loading) {
    return (
      <div className="daily-spinner-container loading">
        <div className="spinner-loader">Loading...</div>
      </div>
    );
  }

  return (
    <div className="daily-spinner-container">
      {error && <div className="error-message">{error}</div>}

      <div className="spinner-header">
        <h1>🎡 Daily Spinning Wheel</h1>
        <p>Win rewards every day! One free spin per 24 hours.</p>
      </div>

      <div className="spinner-content">
        {/* Wheel Section */}
        <div className="wheel-section">
          <div className="wheel-wrapper">
            <div className="wheel-glow"></div>
            <div className="wheel-pointer"></div>
            <div className="wheel" ref={wheelRef} style={{ background: conicGradient }}>
              {wheelSegments.map((segment, index) => {
                const labelAngle = index * sliceAngle + sliceAngle / 2;
                return (
                  <div
                    key={index}
                    className="wheel-label"
                    style={{
                      transform: `translate(-50%, -50%) rotate(${labelAngle}deg) translateY(-118px) rotate(-${labelAngle}deg)`,
                    }}
                  >
                    <span className="slice-value">₹{segment.value}</span>
                  </div>
                );
              })}
              <div className="wheel-center-cap">
                <span>SPIN</span>
              </div>
            </div>
          </div>

          <div className="spin-button-section">
            {!hasSpunToday || extraSpinsBalance > 0 ? (
              <button
                className="spin-button"
                onClick={spinWheel}
                disabled={isSpinning}
              >
                {isSpinning ? 'SPINNING...' : 'SPIN NOW'}
              </button>
            ) : (
              <div className="countdown-section">
                <p className="next-spin-text">Next spin available in:</p>
                <div className="countdown-timer">{timeUntilNextSpin || 'Loading...'}</div>
                <button
                  className="buy-spin-button"
                  onClick={() => handleBuyExtraSpin('card')}
                >
                  💳 Buy Extra Spin - ₹10
                </button>
              </div>
            )}

            {extraSpinsBalance > 0 && (
              <div className="extra-spins-info">
                🎯 Extra Spins: <span className="count">{extraSpinsBalance}</span>
              </div>
            )}
          </div>
        </div>

      </div>

      {/* Popups */}
      {showRewardPopup && (
        <SpinRewardPopup
          amount={reward?.amount}
          transactionId={reward?.transactionId}
          onClose={() => setShowRewardPopup(false)}
        />
      )}

      {showPaymentModal && (
        <PaymentModal
          userId={user.id}
          onSuccess={handlePaymentSuccess}
          onClose={() => setShowPaymentModal(false)}
          paymentOption={paymentOption}
        />
      )}
    </div>
  );
};

export default DailySpinner;
